### ISSUE TITLE
Add Makefile

### ISSUE THREAD

**Issue by mdaverde** [ChristopherLandaverde/Lixt#30]
We're getting to the point where we're adding a lot of commands to the README. We should start moving these commands to a [Makefile](https://www.gnu.org/software/make/manual/html_node/Introduction.html) so we aggregate all the important commands we should know about to one file. 

This also makes it easier to run [CI/CD steps](https://stackify.com/what-is-cicd-whats-important-and-how-to-get-it-right/) on PR requests.

**Comment by ChristopherLandaverde** [comment]
completed.
